### ISSUE TITLE
Will this work

### ISSUE THREAD

**Issue by steve55792** [NapoleonWils0n/rip-record#14]
Hi NapoleonWilson,

I was wondering will this link work with pilfer: https://streamango.com/embed/kepkpqmqsnbmlotf? I tried it and started the running ffmpeg  and it stopped.
Im running ubuntu right now.

**Comment by steve55792** [comment]
I got it working thru Kodi for recording single episodes but if i went thru the terminal  thats when it started running ffmpeg  and it stopped. I used pilfer -i 'https://streamango.com/embed/kepkpqmqsnbmlotf'

**Comment by NapoleonWils0n** [comment]
hi steve

thats web page url
pilfer wont work with that

what you would need to do is open the the developer tools in your browser on the page with the video
usually f12

and switch to the network tab
then reload the page and try and find the m3u8 link

if you google about a bit im sure you find some stuff on finding video links using browser developer tools
and network tab

**Comment by steve55792** [comment]
at least  got it working thru kodi, one at a time. Thank you NapoleonWilson. Ill try that too.

**Comment by steve55792** [comment]
i got it working with the pilfer, going thru what you said to do with the network tab

**Comment by NapoleonWils0n** [comment]
hi steve

nice one mate

that should work on a lot of streaming sites to get the url

**Comment by steve55792** [comment]
i forgot Lol, how do we do a batch record with pilfer?

**Comment by steve55792** [comment]
these files arent live streams its from the websites like  streamago but i will give youtube-dl a try.

**Comment by steve55792** [comment]
im assuming i got to unistall pilfer to install rip-record because i tried youtube.dl and it confuses me how to.

**Comment by NapoleonWils0n** [comment]
hi steve 

dont have to unistall pilfer to install rip-record on linux

dont know about windows
